In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("diabetes_prediction_dataset.csv")
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [3]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [4]:
df.describe()

age  hypertension  heart_disease            bmi  \
count  100000.000000  100000.00000  100000.000000  100000.000000   
mean       41.885856       0.07485       0.039420      27.320767   
std        22.516840       0.26315       0.194593       6.636783   
min         0.080000       0.00000       0.000000      10.010000   
25%        24.000000       0.00000       0.000000      23.630000   
50%        43.000000       0.00000       0.000000      27.320000   
75%        60.000000       0.00000       0.000000      29.580000   
max        80.000000       1.00000       1.000000      95.690000   

         HbA1c_level  blood_glucose_level       diabetes  
count  100000.000000        100000.000000  100000.000000  
mean        5.527507           138.058060       0.085000  
std         1.070672            40.708136       0.278883  
min         3.500000            80.000000       0.000000  
25%         4.800000           100.000000       0.000000  
50%         5.800000           140.000000       0.000000  
75%         6.200000           159.000000       0.000000  
max         9.000000           300.000000       1.000000

# Feature Selection

In [5]:
df["diabetes"].value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

# Balance Data

In [6]:
#balance
# absence_of_diabetes=df[df.diabetes==0]
# presence_of_diabetes=df[df.diabetes==1]
# print(absence_of_diabetes.shape)
# print(presence_of_diabetes.shape)

In [7]:
# absence_of_diabetes=absence_of_diabetes.sample(n=8500)
# absence_of_diabetes

In [8]:
# new_df=pd.concat([absence_of_diabetes,presence_of_diabetes],axis=0)
# new_df

In [9]:
df=df.drop(columns=['smoking_history'])
df

gender   age  hypertension  heart_disease    bmi  HbA1c_level  \
0      Female  80.0             0              1  25.19          6.6   
1      Female  54.0             0              0  27.32          6.6   
2        Male  28.0             0              0  27.32          5.7   
3      Female  36.0             0              0  23.45          5.0   
4        Male  76.0             1              1  20.14          4.8   
...       ...   ...           ...            ...    ...          ...   
99995  Female  80.0             0              0  27.32          6.2   
99996  Female   2.0             0              0  17.37          6.5   
99997    Male  66.0             0              0  27.83          5.7   
99998  Female  24.0             0              0  35.42          4.0   
99999  Female  57.0             0              0  22.43          6.6   

       blood_glucose_level  diabetes  
0                      140         0  
1                       80         0  
2                      158         0  
3                      155         0  
4                      155         0  
...                    ...       ...  
99995                   90         0  
99996                  100         0  
99997                  155         0  
99998                  100         0  
99999                   90         0  

[100000 rows x 8 columns]

In [10]:
df1=pd.get_dummies(df['gender'])
df1

Female   Male  Other
0        True  False  False
1        True  False  False
2       False   True  False
3        True  False  False
4       False   True  False
...       ...    ...    ...
99995    True  False  False
99996    True  False  False
99997   False   True  False
99998    True  False  False
99999    True  False  False

[100000 rows x 3 columns]

In [11]:
# Ensure the dummy variables are numeric
df1= df1.astype(np.int64)

In [12]:
df1.value_counts()

Female  Male  Other
1       0     0        58552
0       1     0        41430
        0     1           18
Name: count, dtype: int64

In [13]:
df1

Female  Male  Other
0           1     0      0
1           1     0      0
2           0     1      0
3           1     0      0
4           0     1      0
...       ...   ...    ...
99995       1     0      0
99996       1     0      0
99997       0     1      0
99998       1     0      0
99999       1     0      0

[100000 rows x 3 columns]

In [14]:
n_df = pd.concat([df, df1], axis=1).reindex(df.index)
n_df

gender   age  hypertension  heart_disease    bmi  HbA1c_level  \
0      Female  80.0             0              1  25.19          6.6   
1      Female  54.0             0              0  27.32          6.6   
2        Male  28.0             0              0  27.32          5.7   
3      Female  36.0             0              0  23.45          5.0   
4        Male  76.0             1              1  20.14          4.8   
...       ...   ...           ...            ...    ...          ...   
99995  Female  80.0             0              0  27.32          6.2   
99996  Female   2.0             0              0  17.37          6.5   
99997    Male  66.0             0              0  27.83          5.7   
99998  Female  24.0             0              0  35.42          4.0   
99999  Female  57.0             0              0  22.43          6.6   

       blood_glucose_level  diabetes  Female  Male  Other  
0                      140         0       1     0      0  
1                       80         0       1     0      0  
2                      158         0       0     1      0  
3                      155         0       1     0      0  
4                      155         0       0     1      0  
...                    ...       ...     ...   ...    ...  
99995                   90         0       1     0      0  
99996                  100         0       1     0      0  
99997                  155         0       0     1      0  
99998                  100         0       1     0      0  
99999                   90         0       1     0      0  

[100000 rows x 11 columns]

In [15]:
df=n_df.drop(columns=['gender'])
df

age  hypertension  heart_disease    bmi  HbA1c_level  \
0      80.0             0              1  25.19          6.6   
1      54.0             0              0  27.32          6.6   
2      28.0             0              0  27.32          5.7   
3      36.0             0              0  23.45          5.0   
4      76.0             1              1  20.14          4.8   
...     ...           ...            ...    ...          ...   
99995  80.0             0              0  27.32          6.2   
99996   2.0             0              0  17.37          6.5   
99997  66.0             0              0  27.83          5.7   
99998  24.0             0              0  35.42          4.0   
99999  57.0             0              0  22.43          6.6   

       blood_glucose_level  diabetes  Female  Male  Other  
0                      140         0       1     0      0  
1                       80         0       1     0      0  
2                      158         0       0     1      0  
3                      155         0       1     0      0  
4                      155         0       0     1      0  
...                    ...       ...     ...   ...    ...  
99995                   90         0       1     0      0  
99996                  100         0       1     0      0  
99997                  155         0       0     1      0  
99998                  100         0       1     0      0  
99999                   90         0       1     0      0  

[100000 rows x 10 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   age                  100000 non-null  float64
 1   hypertension         100000 non-null  int64  
 2   heart_disease        100000 non-null  int64  
 3   bmi                  100000 non-null  float64
 4   HbA1c_level          100000 non-null  float64
 5   blood_glucose_level  100000 non-null  int64  
 6   diabetes             100000 non-null  int64  
 7   Female               100000 non-null  int64  
 8   Male                 100000 non-null  int64  
 9   Other                100000 non-null  int64  
dtypes: float64(3), int64(7)
memory usage: 7.6 MB


In [17]:
x=df.drop(columns='diabetes',axis=1)
y=df['diabetes']

# DataSet Split (train_test Split)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
xtrain

age  hypertension  heart_disease    bmi  HbA1c_level  \
75220  73.0             0              0  24.77          3.5   
48955  80.0             0              0  24.60          5.7   
44966  38.0             0              0  24.33          4.0   
13568  26.0             0              0  18.87          5.0   
92727  61.0             1              0  22.11          4.5   
...     ...           ...            ...    ...          ...   
6265   49.0             0              0  32.98          5.7   
54886  15.0             0              0  28.10          5.0   
76820  42.0             0              0  26.14          5.8   
860    37.0             0              0  24.96          6.2   
15795  23.0             0              0  27.99          5.0   

       blood_glucose_level  Female  Male  Other  
75220                   80       0     1      0  
48955                  145       0     1      0  
44966                  158       1     0      0  
13568                  100       1     0      0  
92727                   85       1     0      0  
...                    ...     ...   ...    ...  
6265                    80       0     1      0  
54886                  159       1     0      0  
76820                   85       0     1      0  
860                    158       1     0      0  
15795                  159       1     0      0  

[80000 rows x 9 columns]

In [21]:
# Standardize the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(xtrain)
X_test_scaled = scaler.transform(xtest)

In [22]:
X_train_scaled

array([[ 1.37871976e+00, -2.86309234e-01, -2.03558690e-01, ...,
        -1.18685419e+00,  1.18734314e+00, -1.41435500e-02],
       [ 1.68986587e+00, -2.86309234e-01, -2.03558690e-01, ...,
        -1.18685419e+00,  1.18734314e+00, -1.41435500e-02],
       [-1.77010751e-01, -2.86309234e-01, -2.03558690e-01, ...,
         8.42563482e-01, -8.42216517e-01, -1.41435500e-02],
       ...,
       [ 7.87021842e-04, -2.86309234e-01, -2.03558690e-01, ...,
        -1.18685419e+00,  1.18734314e+00, -1.41435500e-02],
       [-2.21460194e-01, -2.86309234e-01, -2.03558690e-01, ...,
         8.42563482e-01, -8.42216517e-01, -1.41435500e-02],
       [-8.43752400e-01, -2.86309234e-01, -2.03558690e-01, ...,
         8.42563482e-01, -8.42216517e-01, -1.41435500e-02]])

# LogisticRegression

In [23]:
from sklearn.linear_model import LogisticRegression
LoR=LogisticRegression()

In [24]:
LoR.fit(X_train_scaled,ytrain)

LogisticRegression()

In [25]:
LoR.score(X_test_scaled,ytest)

0.95875

In [26]:
pred=LoR.predict(X_test_scaled)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import classification_report


In [28]:
lor_cr=classification_report(ytest,pred)
print(lor_cr)

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     18292
           1       0.86      0.61      0.72      1708

    accuracy                           0.96     20000
   macro avg       0.91      0.80      0.85     20000
weighted avg       0.96      0.96      0.96     20000



# #  KNN classifier

In [29]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

knn = KNeighborsClassifier(n_neighbors=2) 
knn.fit(X_train_scaled, ytrain)

KNeighborsClassifier(n_neighbors=2)

In [30]:
knn.score(X_test_scaled,ytest)

0.96365

In [31]:
knnpred=LoR.predict(X_test_scaled)
knnpred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
knn_cr=classification_report(ytest,knnpred)
print(knn_cr)

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     18292
           1       0.86      0.61      0.72      1708

    accuracy                           0.96     20000
   macro avg       0.91      0.80      0.85     20000
weighted avg       0.96      0.96      0.96     20000



In [33]:
# Function to accept user input
def get_user_input():
    input_data = []
    feature_names = x.columns
    for feature in feature_names:
        value = float(input(f'Enter value for {feature}: '))
        input_data.append(value)
    return input_data

user_input = get_user_input()
print(f'User input: {user_input}')

Enter value for age:  45
Enter value for hypertension:  1
Enter value for heart_disease:  1
Enter value for bmi:  144
Enter value for HbA1c_level:  144
Enter value for blood_glucose_level:  111
Enter value for Female:  1
Enter value for Male:  0
Enter value for Other:  0


User input: [45.0, 1.0, 1.0, 144.0, 144.0, 111.0, 1.0, 0.0, 0.0]


In [34]:
# Transform the user input using the same scaler
user_input_r = np.array(user_input).reshape(1, -1)
user_input_r



array([[ 45.,   1.,   1., 144., 144., 111.,   1.,   0.,   0.]])

In [35]:
user_input_s = scaler.transform(user_input_r)
user_input_s

C:\Users\Momin\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 1.34135352e-01,  3.49272702e+00,  4.91258810e+00,
         1.76367542e+01,  1.29323061e+02, -6.64107943e-01,
         8.42563482e-01, -8.42216517e-01, -1.41435500e-02]])

In [36]:
# Make prediction
prediction = knn.predict(user_input_s)
print(f'Prediction: {"Diabetes" if prediction[0] == 1 else "No Diabetes"}')

Prediction: Diabetes


In [37]:
# import pickle

# # Save the trained model and scaler to a file
# model_path = 'model.pkl'
# with open(model_path, 'wb') as model_file:
#     pickle.dump({'model': knn, 'scaler': scaler, 'features': x.columns.tolist()}, model_file)

In [38]:
# Save the trained model
# import joblib
# joblib.dump(knn, 'knn_model.pkl')
# joblib.dump(scaler, 'scaler.pkl')

In [39]:
# import sklearn
# print(sklearn.__version__)